baseurl:     ''
exclude:     [README.md, Gemfile, Gemfile.lock, vendor, _site]
permalink:   /articles/:title
pygments:    true
markdown:    kramdown
encoding:    UTF-8
title:       heidsoft
url:         "https://heidsoft.github.io/"
description: "云计算与大数据"
